---
events:
  init:
    max_inst: 32
    loop_id: 32
    pid: 32
  load:
    size: 24
    instr: 32
    addr: 64
    value: 64
  store:
    size: 24
    instr: 32
    addr: 64
  alloc:
    inst_id: 24 # FIXME: this is problematic
    size: 32
    ptr: 64
  realloc:
    inst_id: 24 # FIXME: this is problematic
    size: 32
    old_ptr: 64
    new_ptr: 64
  free:
    ptr: 64
  target_loop_invoc:
    # No arg
  target_loop_iter:
    # No arg
  target_loop_exit:
    # No arg
  loop_entry:
    loop_id: 32
  loop_exit:
    loop_id: 32
  loop_iter_ctx:
    loop_id: 32
  func_entry:
    function_id: 32
  func_exit:
    function_id: 32
  points_to_inst:
    inst_id: 32
    ptr: 64
  points_to_arg:
    arg_id: 32
    ptr: 64
  finished:
    # no arg
