---
module: ObjLifetimeMod
description: "Object Lifetime Module"
events:
  init: [loop_id, pid]
  alloc: [inst_id, size, ptr]
  free: [ptr]
  target_loop_invoc: []
  target_loop_iter: []
  target_loop_exit: []
  func_entry: [function_id]
  func_exit: [function_id]
  finished: []
