---
module: PrivateerProfiler
description: "Privateer profiler"
events:
  init: [loop_id, pid]
  load: [instr, value]
  alloc: [inst_id, size, ptr]
  realloc: [inst_id, size, old_ptr, new_ptr]
  free: [ptr]
  loop_entry: [loop_id]
  loop_exit: [loop_id]
  loop_iter_ctx: [loop_id]
  func_entry: [function_id]
  func_exit: [function_id]
  points_to_inst: [inst_id, ptr]
  points_to_arg: [arg_id, ptr]
  stack_lifetime_start: [inst_id, size, ptr]
  stack_lifetime_end: [ptr]
  finished: []
