---
module: DepMod
description: "Dependence module"
events:
  init: [loop_id, pid]
  load: [size, instr, addr]
  store: [size, instr, addr]
  alloc: [size, ptr]
  loop_entry: [loop_id]
  loop_iter_ctx: []
  loop_exit: [loop_id]
  # func_entry: [function_id] # optional if tracking context
  # func_exit: [function_id] # optional if tracking context
  finished: []
...
