BINARY=benchmark
PLAIN=$(BINARY).plain
CANON=$(BINARY)

LIBS?=

ifdef SPEC_DEFAULTS
OBJFILES_BC = $(OBJS)
else
OBJFILES_BC?= $(shell find . -name \*.c | sed -e "s/\.c/.bc/" ) $(shell find . -name \*.C | sed -e "s/\.C/.bc/" ) $(shell find . -name \*.cpp | sed -e "s/\.cpp/.bc/" )  $(shell find . -name \*.cc | sed -e "s/\.cc/.bc/" )
endif

BENCH_NAME?=$(shell cd .. && basename `pwd`)
BENCH_DIR?= ../../$(BENCH_NAME)

.SECONDARY:

-include ../compile_info
-include ../execInfo

CC?= gcc
CXX?= g++
LLVM_CC?= clang
LLVM_CXX?= clang++
LLVM_LINK?= llvm-link
LLVM_OPT?= opt

ARGS?=$(TRAINARGS)
LLVM_CFLAGS?=-O1 -g -c -emit-llvm $(PREPROCESSOR_OPTIONS) $(PREPROCESSING_OPTIONS) $(DEBUG) -Xclang -disable-llvm-passes $(FINAL_CFLAGS) $(FINAL_CXXFLAGS) -fno-builtin ### !!! FIXME: temp change
TRANSFORMATIONS_BEFORE_PARALLELIZATION=-mem2reg -simplifycfg -simplifycfg-sink-common=false -instcombine -tailcallelim -loop-simplify -lcssa -licm -loop-unswitch -globalopt -instcombine -ipsccp -gvn -dse -adce -loop-simplify -lcssa -indvars -loop-deletion -instcombine -indvars
OPT_LEVEL=-O3


$(PLAIN).o3.out : $(PLAIN).o3.exe
	date
	rm -f $(PLAIN).o3.out original.time
	$(SETUP)
	./$(PLAIN).o3.exe $(TESTARGS) >$@ 2>&1
	$(CLEANUP)
	date

$(PLAIN).o3.exe : $(PLAIN).o3.bc
	date
	$(LLVM_OPT) -strip $^ -o $(PLAIN).o3.striped.bc
	$(LLVM_CXX) -O3 $(CXXOPTIMIZE) $(COPTIMIZE) -lm $(LIBS) $(PLAIN).o3.striped.bc -o $@
	date

#
# loop profile
#

%.loopProf.out : %.loopProf.exe
	date
	$(SETUP)
	$(PROFILESETUP)
	./$*.loopProf.exe $(PROFILEARGS) >rabbit2 2>&1
	mv loopProf.out $@
	$(CLEANUP)
	date

%.loopProf.exe : export LINKING_OPTS = $(LINKING_POSTOPTIONS)
%.loopProf.exe : %.bc $(LOOPPROFLIBS)
	date
	rm -f $*.loopProf.time $*.loopProf.out $*.loopProf.exe
	loop-profile $<
	date

#
# SLAMP profile
#

%.result.slamp.profile: export LINKING_OPTS = $(LINKING_POSTOPTIONS)
%.result.slamp.profile: $(CANON).bc
	date
	$(SETUP)
	$(PROFILESETUP)
	- cp $*.loopProf.out loopProf.out
	DEFAULT_LDFLAGS="$(DEFAULT_LDFLAGS)" DEFAULT_LIBS="$(DEFAULT_LIBS)" PROFILEARGS="$(ARGS) $(PROFILEARGS)" SETUP="$(SETUP) $(PROFILESETUP)" \
	slamp-driver $*.bc $(TARGET_FCN) $(TARGET_LOOP) #> rabbit6 2>&1
	mv result.slamp.profile $@
	rm -f loopProf.out
	$(CLEANUP)
	date

%.o3.bc :%.bc
	date
	$(LLVM_OPT) -O3 $< -o $@
	date

%.opt.bc :%.bc
	date
	$(LLVM_OPT) $(TRANSFORMATIONS_BEFORE_PARALLELIZATION) $< -o $@
	date

$(PLAIN).bc : $(OBJFILES_BC)
	date
	$(LLVM_LINK) $(LLVM_LINK_FLAGS) $^ -o $@
	date

$(CANON).bc : $(PLAIN).opt.bc
	cp $< $@

%.bc : %.c
	$(LLVM_CC) $(LLVM_CFLAGS) $< -o $@
	$(LLVM_OPT) $(TRANSFORMATIONS_BEFORE_PARALLELIZATION) $@ -o $@

%.bc : %.C
	$(LLVM_CC) $(LLVM_CFLAGS) $< -o $@
	$(LLVM_OPT) $(TRANSFORMATIONS_BEFORE_PARALLELIZATION) $@ -o $@

%.bc : %.cpp
	$(LLVM_CXX) $(LLVM_CFLAGS) $< -o $@
	$(LLVM_OPT) $(TRANSFORMATIONS_BEFORE_PARALLELIZATION) $@ -o $@

%.bc : %.cc
	$(LLVM_CXX) $(LLVM_CFLAGS) $< -o $@
	$(LLVM_OPT) $(TRANSFORMATIONS_BEFORE_PARALLELIZATION) $@ -o $@

%.exe : %.bc
	$(LLVM_CXX) -O3 $< -lm -lstdc++ $(LDFLAGS) $(QUEUES) $(LAMP) $(EDGEPROF) $(SPPROF) $(SPEX) -lrt -o $@

clean :
	- $(CLEANUP)
	rm -f *.o *.ll *.bc *.pdf *.dot $(CANON).* $(CANON).opt.* *.time *.dump compare1.out rabbit* *.out
	find . -type f -name '*.bc' -delete
