name: Regression Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore cache from LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-install
          key: llvm-9.0.1-${{ runner.os }}
          restore-keys: |
            llvm-9.0.1-${{ runner.os }}

      - name: Restore cache from Noelle
        id: cache-noelle
        uses: actions/cache@v3
        with:
          path: noelle-install
          key: noelle-${{ runner.os }}
          restore-keys: |
            noelle-${{ runner.os }}
          
      - name: Restore cache from PROMPT
        id: cache-prompt
        uses: actions/cache@v3
        with:
          path: PROMPT/install
          key: ${{ runner.os }}-prompt-install-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-prompt-install-

      - name: Install system dependences
        run: |
          sudo apt-get install -y build-essential libboost-all-dev libunwind-dev binutils-dev

      - name: Run regression tests
        run: |
          LLVM_INSTALL=$(realpath llvm-install)
          PROMPT_INSTALL=$(realpath PROMPT/install)
          source ${PROMPT_INSTALL}/PROMPT.rc
          export PATH=${LLVM_INSTALL}/bin/:${PATH}

          test_dirs=("test1")
          for name in "${test_dirs[@]}"; do
            pushd tests/regression/${name}/src
            make benchmark.result.slamp.profile
            diff benchmark.result.slamp.profile ../profiles/gt.profile
            popd
          done
